apiVersion: v1
appVersion: 1.0.1
description: Flagger is a progressive delivery operator for Kubernetes
engine: gotpl
home: https://flagger.app
icon: https://raw.githubusercontent.com/weaveworks/flagger/master/docs/logo/weaveworks.png
keywords:
- flagger
- istio
- appmesh
- linkerd
- gloo
- contour
- nginx
- gitops
- canary
kubeVersion: '>=1.11.0-0'
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
  url: https://github.com/stefanprodan
name: flagger
sources:
- https://github.com/weaveworks/flagger
version: 1.0.1
